version: "3.7"
services:
  db:
    image: mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql-batch
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=springbatch
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    volumes:
      - /Users/Shared/data/mysql-batch:/var/lib/mysql